spring:
  application:
    name: sz-mybatis
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?useSSL=true
      username: root
      password: 1234
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
mybatis:
  type-aliases-package: com.sz.mybatis.entity

server:
  port: 9002

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
