server:
  port: 9003

spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alan-oauth?useSSL=true
    username: root
    password: 1234
    initial-size: 5
    min-idle: 5
    max-active: 10
    max-wait: 60000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/